import React, { useState } from 'react';

// Types for AI Builder content types
interface ContentType {
  key: string;
  label: string;
}

const contentTypes: ContentType[] = [
  { key: 'test', label: 'Tests' },
  { key: 'assessment', label: 'Assessments' },
  { key: 'exploration', label: 'Explorations' },
  { key: 'course', label: 'Courses' }
];

const AIBuilderPanel: React.FC = () => {
  const [activeType, setActiveType] = useState<string>('test');
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [content, setContent] = useState('');
  const [submissions, setSubmissions] = useState<any[]>([]);

  // Simulate an AI powered content creation function
  const generateContent = async (type: string, title: string, description: string) => {
    // This is a stub. In a real system, you would call your AI service API here.
    return `AI Generated content for ${type} titled '${title}':\n\n${description}\n\n[Detailed content generated by AI]`;
  };

  const handleGenerate = async () => {
    const generated = await generateContent(activeType, title, description);
    setContent(generated);
  };

  const handleSubmit = () => {
    const newContent = {
      type: activeType,
      title,
      description,
      content
    };
    setSubmissions([...submissions, newContent]);
    // Reset fields
    setTitle('');
    setDescription('');
    setContent('');
    alert(`New ${activeType} created successfully!`);
  };

  return (
    <div className="p-6 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold mb-4">AI Builder Panel</h1>
      <div className="mb-4">
        {contentTypes.map((type) => (
          <button
            key={type.key}
            onClick={() => setActiveType(type.key)}
            className={`mr-2 px-4 py-2 rounded ${activeType === type.key ? 'bg-blue-600 text-white' : 'bg-white text-blue-600 border border-blue-600'}`}
          >
            {type.label}
          </button>
        ))}
      </div>
      <div className="bg-white p-4 rounded shadow">
        <h2 className="text-xl font-semibold mb-2">Create New {contentTypes.find(t => t.key === activeType)?.label}</h2>
        <div className="mb-2">
          <label className="block mb-1">Title</label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full p-2 border rounded"
            placeholder="Enter title"
          />
        </div>
        <div className="mb-2">
          <label className="block mb-1">Description</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="w-full p-2 border rounded"
            placeholder="Enter description"
            rows={3}
          />
        </div>
        <div className="flex items-center mb-4 space-x-2">
          <button
            onClick={handleGenerate}
            className="px-4 py-2 bg-green-600 text-white rounded"
          >
            Generate Content
          </button>
          {content && <span className="text-sm text-gray-600">Content generated!</span>}
        </div>
        {content && (
          <div className="mb-4">
            <label className="block mb-1">Content Preview</label>
            <textarea
              value={content}
              readOnly
              className="w-full p-2 border rounded bg-gray-50"
              rows={6}
            />
          </div>
        )}
        <button
          onClick={handleSubmit}
          className="px-4 py-2 bg-blue-600 text-white rounded"
        >
          Submit {contentTypes.find(t => t.key === activeType)?.label}
        </button>
      </div>

      {submissions.length > 0 && (
        <div className="mt-8">
          <h3 className="text-xl font-semibold mb-4">Submitted Items</h3>
          {submissions.map((item, index) => (
            <div key={index} className="mb-4 p-4 border rounded bg-white">
              <h4 className="text-lg font-bold">[{item.type.toUpperCase()}] {item.title}</h4>
              <p className="text-gray-600 mb-2">{item.description}</p>
              <pre className="bg-gray-100 p-2 rounded whitespace-pre-wrap text-sm">{item.content}</pre>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default AIBuilderPanel;
