// This file is automatically generated. Do not edit it directly.
import { AuthTables } from './types/modules/auth.types';
import { AssessmentTables } from './types/modules/assessment.types';
import { ContentTables } from './types/modules/content.types';
import { CommunityTables } from './types/modules/community.types';
import { AiTables } from './types/modules/ai.types';
import { PaymentsTables } from './types/modules/payments.types';
import { PlatformTables } from './types/modules/platform.types';

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "12.2.3 (519615d)"
  }
  public: {
    Tables: AuthTables &
            AssessmentTables &
            ContentTables &
            CommunityTables &
            AiTables &
            PaymentsTables &
            PlatformTables;
    Views: {
      dashboard_view: PlatformTables['dashboard_view'];
      user_journal_stats: ContentTables['user_journal_stats'];
    }
    Functions: {
      award_crystals: {
        Args: { crystal_amount: number; user_id_input: string }
        Returns: undefined
      }
      complete_exploration_session: {
        Args: { final_analysis_input: Json; session_id_input: string }
        Returns: undefined
      }
      create_assessment_with_questions: {
        Args: {
          _title: string
          _description: string
          _type: string
          _visibility: string
          _ai_provider: string
          _ai_model: string
          _ai_prompt: string
          _questions: Json
        }
        Returns: undefined
      }
      get_admin_safe_profiles: {
        Args: Record<PropertyKey, never>
        Returns: {
          created_at: string
          email: string
          is_admin_backup: boolean
          last_sign_in_at: string
          role: string
          updated_at: string
          user_id: string
        }[]
      }
      get_agent_configuration_by_id: {
        Args: { config_id: string }
        Returns: {
          agent_pattern: string
          agent_roles: Json | null
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string
          is_active: boolean | null
          name: string
          sequential_agents: Json | null
          system_prompt: string
          updated_at: string | null
          updated_by: string | null
        }
      }
      get_agent_configurations: {
        Args: Record<PropertyKey, never>
        Returns: {
          agent_pattern: string
          agent_roles: Json | null
          created_at: string | null
          created_by: string | null
          description: string | null
          id: string
          is_active: boolean | null
          name: string
          sequential_agents: Json | null
          system_prompt: string
          updated_at: string | null
          updated_by: string | null
        }[]
      }
      get_dashboard_data: {
        Args: { p_user_id: string }
        Returns: {
          exploration_completed: boolean
          exploration_last_activity: string
          exploration_progress: number
          next_step_cta: string
          next_step_description: string
          next_step_link: string
          next_step_title: string
          overall_progress: number
          personality_completed: boolean
          personality_last_activity: string
          personality_progress: number
          user_id: string
          values_completed: boolean
          values_last_activity: string
          values_progress: number
        }[]
      }
      get_enhanced_dashboard_data: {
        Args: { p_user_id: string }
        Returns: {
          completed_explorations: number
          crystals_count: number
          current_streak: number
          display_name: string
          growth_areas: string[]
          level_progress: number
          next_milestone: Json
          personality_type: string
          recent_achievements: Json
          subscription_tier: string
          total_breathing_minutes: number
          user_id: string
        }[]
      }
      get_or_create_conversation: {
        Args: { user1_id: string; user2_id: string }
        Returns: string
      }
      get_user_usage_stats: {
        Args: { user_id: string }
        Returns: Json
      }
      is_admin: {
        Args: { uid: string }
        Returns: boolean
      }
      save_personality_assessment: {
        Args: {
          answers_input: Json
          results_input: Json
          user_id_input: string
        }
        Returns: string
      }
      start_exploration_session: {
        Args: { exploration_id_input: string; user_id_input: string }
        Returns: string
      }
      update_exploration_progress: {
        Args: {
          answer_input: string
          question_index_input: number
          session_id_input: string
        }
        Returns: undefined
      }
      update_platform_setting: {
        Args: { setting_key: string; setting_value: string }
        Returns: boolean
      }
      update_post_status_secure: {
        Args: { p_post_id: string; p_new_status: string }
        Returns: undefined
      }
      update_user_ban_status_secure: {
        Args: { target_user_id: string; new_status: boolean }
        Returns: undefined
      }
      update_user_role_secure: {
        Args: { new_role: string; target_user_id: string }
        Returns: undefined
      }
      update_user_subscription_secure: {
        Args: { new_tier: string; target_user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database['public']

export type Tables<
  TableName extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])
> = (PublicSchema['Tables'] & PublicSchema['Views'])[TableName] extends {
  Row: infer R
}
  ? R
  : never

export type TablesInsert<
  TableName extends keyof PublicSchema['Tables']
> = PublicSchema['Tables'][TableName] extends {
  Insert: infer I
}
  ? I
  : never

export type TablesUpdate<
  TableName extends keyof PublicSchema['Tables']
> = PublicSchema['Tables'][TableName] extends {
  Update: infer U
}
  ? U
  : never

export type Enums<
  EnumName extends keyof PublicSchema['Enums']
> = PublicSchema['Enums'][EnumName]

export type CompositeTypes<
  CompositeTypeName extends keyof PublicSchema['CompositeTypes']
> = PublicSchema['CompositeTypes'][CompositeTypeName]

export const Constants = {
  public: {
    Enums: {},
  },
} as const