import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/hooks/use-toast';
import { 
  Star,
  TrendingUp,
  Heart,
  Brain,
  Target,
  Lightbulb,
  Share2,
  Download,
  RotateCcw,
  Sparkles,
  Award,
  CheckCircle,
  ArrowRight
} from 'lucide-react';
import { motion } from 'framer-motion';

interface AssessmentResult {
  primary_type?: string;
  secondary_type?: string;
  scores?: Record<string, number>;
  confidence_score?: number;
  total_score?: number;
  strengths?: string[];
  growth_areas?: string[];
  recommendations?: string[];
}

interface AssessmentResultsProps {
  results: AssessmentResult;
  assessmentTitle: string;
  assessmentCategory: string;
  onRetake?: () => void;
  onNewAssessment?: () => void;
  onShare?: () => void;
}

export const AssessmentResults: React.FC<AssessmentResultsProps> = ({
  results,
  assessmentTitle,
  assessmentCategory,
  onRetake,
  onNewAssessment,
  onShare
}) => {
  const [showDetailedResults, setShowDetailedResults] = useState(false);
  const { toast } = useToast();

  // Result type descriptions
  const resultDescriptions: Record<string, { title: string; description: string; color: string }> = {
    extrovert: {
      title: "The Energizer",
      description: "You gain energy from social interactions and thrive in collaborative environments. Your enthusiasm and outward focus make you a natural connector.",
      color: "from-orange-400 to-red-400"
    },
    introvert: {
      title: "The Reflector",
      description: "You process internally and gain energy from solitude. Your thoughtful approach and deep focus are valuable strengths in many situations.",
      color: "from-blue-400 to-purple-400"
    },
    thinking: {
      title: "The Analyst",
      description: "You make decisions based on logic and objective analysis. Your rational approach helps you see situations clearly and fairly.",
      color: "from-green-400 to-teal-400"
    },
    feeling: {
      title: "The Harmonizer",
      description: "You consider people and values when making decisions. Your empathetic nature helps create harmony and understanding.",
      color: "from-pink-400 to-rose-400"
    },
    judging: {
      title: "The Organizer",
      description: "You prefer structure and closure. Your planning abilities and decisive nature help bring order and completion to projects.",
      color: "from-indigo-400 to-blue-400"
    },
    perceiving: {
      title: "The Adapter",
      description: "You prefer flexibility and openness. Your spontaneous nature and adaptability help you navigate changing situations with ease.",
      color: "from-yellow-400 to-orange-400"
    },
    sensing: {
      title: "The Realist",
      description: "You focus on concrete details and present realities. Your practical approach and attention to facts keep projects grounded.",
      color: "from-emerald-400 to-green-400"
    },
    intuitive: {
      title: "The Visionary",
      description: "You see patterns and possibilities. Your innovative thinking and future focus help generate new ideas and solutions.",
      color: "from-violet-400 to-purple-400"
    }
  };

  const getPrimaryResult = () => {
    if (results.primary_type && resultDescriptions[results.primary_type]) {
      return resultDescriptions[results.primary_type];
    }
    return {
      title: "Your Unique Profile",
      description: "You have a distinctive combination of traits that make you uniquely you.",
      color: "from-primary to-secondary"
    };
  };

  const primaryResult = getPrimaryResult();

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: `My ${assessmentTitle} Results`,
        text: `I just completed the ${assessmentTitle} and discovered I'm ${primaryResult.title}! Check it out:`,
        url: window.location.href
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      toast({
        title: "Link Copied",
        description: "Assessment link copied to clipboard!"
      });
    }
    onShare?.();
  };

  const downloadResults = () => {
    const resultsText = `
${assessmentTitle} Results

Primary Type: ${primaryResult.title}
${primaryResult.description}

Confidence Score: ${results.confidence_score?.toFixed(1) || 'N/A'}%

${results.strengths ? `Strengths:
${results.strengths.map(s => `• ${s}`).join('\n')}` : ''}

${results.growth_areas ? `Growth Areas:
${results.growth_areas.map(g => `• ${g}`).join('\n')}` : ''}

${results.recommendations ? `Recommendations:
${results.recommendations.map(r => `• ${r}`).join('\n')}` : ''}

Generated by NewMe - Your AI Growth Companion
    `.trim();

    const blob = new Blob([resultsText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${assessmentTitle.replace(/\s+/g, '_')}_Results.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Results Downloaded",
      description: "Your assessment results have been saved!"
    });
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Celebration Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center space-y-4"
      >
        <div className="flex items-center justify-center">
          <div className="relative">
            <div className="absolute inset-0 animate-pulse bg-gradient-to-r from-primary/20 to-secondary/20 rounded-full blur-xl"></div>
            <div className="relative bg-gradient-to-r from-primary to-secondary p-6 rounded-full">
              <Award className="w-12 h-12 text-white" />
            </div>
          </div>
        </div>
        
        <div>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
            Assessment Complete!
          </h1>
          <p className="text-muted-foreground mt-2">
            Discover your personalized insights below
          </p>
        </div>
      </motion.div>

      {/* Primary Result Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ delay: 0.2 }}
      >
        <Card className="glass overflow-hidden">
          <div className={`h-2 bg-gradient-to-r ${primaryResult.color}`}></div>
          <CardHeader className="text-center space-y-4">
            <div>
              <Badge variant="secondary" className="mb-3">
                {assessmentCategory}
              </Badge>
              <CardTitle className="text-3xl">{primaryResult.title}</CardTitle>
              <p className="text-muted-foreground text-lg mt-2 leading-relaxed">
                {primaryResult.description}
              </p>
            </div>
            
            {results.confidence_score && (
              <div className="space-y-2">
                <div className="flex items-center justify-center gap-2">
                  <Star className="w-5 h-5 text-yellow-500" />
                  <span className="text-2xl font-bold">
                    {results.confidence_score.toFixed(1)}%
                  </span>
                  <span className="text-muted-foreground">confidence</span>
                </div>
                <Progress 
                  value={results.confidence_score} 
                  className="w-full max-w-md mx-auto" 
                />
              </div>
            )}
          </CardHeader>
        </Card>
      </motion.div>

      {/* Detailed Scores (if available) */}
      {results.scores && Object.keys(results.scores).length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
        >
          <Card className="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5" />
                Detailed Breakdown
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {Object.entries(results.scores).map(([trait, score]) => {
                const percentage = Math.min(100, Math.max(0, (score / 3) * 100)); // Assuming max score of 3 per question
                const traitInfo = resultDescriptions[trait];
                
                return (
                  <div key={trait} className="space-y-2">
                    <div className="flex justify-between items-center">
                      <span className="font-medium capitalize">
                        {trait.replace('_', ' ')}
                      </span>
                      <span className="text-sm text-muted-foreground">
                        {percentage.toFixed(1)}%
                      </span>
                    </div>
                    <Progress value={percentage} className="h-2" />
                    {traitInfo && (
                      <p className="text-sm text-muted-foreground">
                        {traitInfo.description}
                      </p>
                    )}
                  </div>
                );
              })}
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Insights Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        {results.strengths && results.strengths.length > 0 && (
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.6 }}
          >
            <Card className="glass h-full">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-green-600">
                  <CheckCircle className="w-5 h-5" />
                  Your Strengths
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3">
                  {results.strengths.map((strength, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <Sparkles className="w-4 h-4 text-yellow-500 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{strength}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {/* Growth Areas */}
        {results.growth_areas && results.growth_areas.length > 0 && (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.8 }}
          >
            <Card className="glass h-full">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-blue-600">
                  <TrendingUp className="w-5 h-5" />
                  Growth Opportunities
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3">
                  {results.growth_areas.map((area, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <Target className="w-4 h-4 text-blue-500 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{area}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </motion.div>
        )}
      </div>

      {/* Recommendations */}
      {results.recommendations && results.recommendations.length > 0 && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1.0 }}
        >
          <Card className="glass">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-purple-600">
                <Lightbulb className="w-5 h-5" />
                Personalized Recommendations
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                {results.recommendations.map((recommendation, index) => (
                  <div key={index} className="p-4 bg-muted/50 rounded-lg">
                    <p className="text-sm">{recommendation}</p>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>
      )}

      {/* Action Buttons */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 1.2 }}
        className="flex flex-col sm:flex-row gap-4 justify-center pt-6"
      >
        <Button onClick={handleShare} variant="outline" className="flex items-center gap-2">
          <Share2 className="w-4 h-4" />
          Share Results
        </Button>
        
        <Button onClick={downloadResults} variant="outline" className="flex items-center gap-2">
          <Download className="w-4 h-4" />
          Download PDF
        </Button>
        
        {onRetake && (
          <Button onClick={onRetake} variant="outline" className="flex items-center gap-2">
            <RotateCcw className="w-4 h-4" />
            Retake Assessment
          </Button>
        )}
        
        <Button onClick={onNewAssessment} className="flex items-center gap-2">
          <ArrowRight className="w-4 h-4" />
          Try Another Assessment
        </Button>
      </motion.div>

      {/* Next Steps */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 1.4 }}
      >
        <Card className="glass border-primary/20">
          <CardContent className="p-6 text-center space-y-4">
            <h3 className="text-xl font-semibold">Continue Your Growth Journey</h3>
            <p className="text-muted-foreground">
              Ready to dive deeper? Explore our personalized growth programs and connect with your AI companion.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Button className="bg-gradient-to-r from-primary to-secondary">
                Start Free Trial
              </Button>
              <Button variant="outline">
                Explore Programs
              </Button>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  );
};

export default AssessmentResults;
